
create a budget , budget action, iam role and iam policy




Resources:
  BudgetRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: RoleForBudget
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - budgets.amazonaws.com
            Action:
            - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Sid: Stmt922116106069
              Effect: Allow
              Action: 
                - aws-portal:ModifyBilling
                - ec2:DescribeInstances
                - iam:*
                - organizations:ListAccounts
                - organizations:ListOrganizationalUnitsForParent
                - organizations:ListPolicies
                - organizations:ListRoots
                - rds:DescribeDBInstances
                - sns:ListTopics
              Resource: "*"
  BudgetPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: PolicyForBudget 
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ec2:DescribeImages
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:DescribeInstances
              - ec2:DescribeVpcs
              - ec2:CreateKeyPair
              - ec2:CreateSecurityGroup
              - ec2:DescribeInstanceTypes
              - ec2:DescribeSubnets
              - ec2:DescribeKeyPairs
              - ec2:DescribeSecurityGroups
            Resource: "*"
          - Effect: Deny
            Action: 
              - rds:*
              - s3:*
              - vpc:*
            Resource: "*"

          - Effect: Deny
            Action: ec2:RunInstances
            Resource: "*"
            Condition:
              ForAnyValue:StringNotEquals:
                ec2:InstanceType: t2.micro
  Budget:
    Type: "AWS::Budgets::Budget"
    Properties:
      Budget:
        BudgetLimit:
          Amount: 500
          Unit: USD
        TimeUnit: MONTHLY
        TimePeriod:
          Start: 1627776000
        BudgetType: COST
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 95
          Subscribers:
            - SubscriptionType: EMAIL
              Address: anil.sriram@relevancelab.com
            - SubscriptionType: EMAIL
              Address: mamatha.anand@relevancelab.com
            - SubscriptionType: EMAIL
              Address: suresh.panneerselvam@relevancelab.com           
            - SubscriptionType: EMAIL
              Address: shankar.soundarpandai@relevancelab.com
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 80
          Subscribers:
          - SubscriptionType: EMAIL
            Address: anil.sriram@relevancelab.com
          - SubscriptionType: EMAIL
            Address: mamatha.anand@relevancelab.com       
          - SubscriptionType: EMAIL
            Address: suresh.panneerselvam@relevancelab.com           
          - SubscriptionType: EMAIL
            Address: shankar.soundarpandai@relevancelab.com
  BudgetAction:
    Type: AWS::Budgets::BudgetsAction
    Properties:
      ActionThreshold:
        Type: PERCENTAGE
        Value: 99.00
      ActionType: APPLY_IAM_POLICY
      ApprovalModel: AUTOMATIC
      BudgetName: !Ref Budget
      Definition:
        IamActionDefinition:
          PolicyArn: !Ref BudgetPolicy  
          Users:
            - dheepa
            - haritha
            - kumaran
            - manikandan
            - prasanna
            - suresh
            - shankar
      ExecutionRoleArn: !GetAtt BudgetRole.Arn
      NotificationType:  ACTUAL
      Subscribers:
      - Type: EMAIL
        Address: anil.sriram@relevancelab.com
      - Type: EMAIL
        Address: mamatha.anand@relevancelab.com      
      - Type: EMAIL
        Address: suresh.panneerselvam@relevancelab.com
      - Type: EMAIL
        Address: shankar.soundarpandai@relevancelab.com
Outputs:
  BudgetId:
    Value: !Ref Budget




    
  




    
  
